spring:
  application.name: accounts-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;user=SA;password=yourStrong(!)Password;encrypt=false;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: GSSAPI
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_uncommitted
      enable-auto-commit: false
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: account-service-tx-
  output.ansi.enabled: ALWAYS

logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"
#  level:
#    org.springframework.transaction: trace
#    org.springframework.kafka.transaction: debug
#logging.level.org.springframework.transaction=trace
#logging.level.org.springframework.kafka.transaction=debug
#logging.level.org.springframework.jdbc=debug